version: '3'
services:
  nginx: 
    ports: 
      - '80:80'
      - '443:443'
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs            
    networks:
      - app-network
  server:
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html  
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email kevinbriggs1@gmail.com --agree-tos --staging -d mrteacherkevin.rocks 
volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /root/mrteacherkevin/client/public
      o: bind        
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /root/mrteacherkevin/nginx/dhparam/
      o: bind
networks:
  app-network:
    driver: bridge
