version: '3'
services:
  mongo:
    build:
      dockerfile: Dockerfile
      context: ./db
    restart: always
    volumes:
      - ./db/data:/data/db
    ports: 
      - '27017:27017'
    container_name: mrtk_mongo
  server: 
    depends_on:
      - mongo 
    links:
      - mongo 
  client:
    build:
      dockerfile: Dockerfile.dev
  nginx:
    ports:
      - '3000:80'