version: '3'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
    container_name: mrtk_nginx
    depends_on: 
      - server
      - client
  server:
    build:
      context: ./server
    container_name: mrtk_server 
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file:
      - ./server/.env
  client:
    build:
      context: ./client
    container_name: mrtk_client
    volumes:
      - /app/node_modules
      - ./client:/app
