version: '3'
services:
  mongo:
    build:
      dockerfile: Dockerfile
      context: ./db
    restart: always
    volumes:
      - ./db/data:/data/db
    ports: 
      - '27018:27017'
    container_name: mrtk_mongo
  server: 
    depends_on:
      - mongo 
    build:
      dockerfile: Dockerfile.dev
    links:
      - mongo 
  client:
    build:
      dockerfile: Dockerfile.dev
  nginx:
    ports:
      - '3000:80'
    volumes: 
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf